// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:484992258162:web:44e4a5f999090d30b2f2eb',
    messagingSenderId: '484992258162',
    projectId: 'notifi-536aa',
    authDomain: 'notifi-536aa.firebaseapp.com',
    storageBucket: 'notifi-536aa.firebasestorage.app',
    measurementId: 'G-WM7P1S3DYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5PTcu416FrmaNfxEoHlfNH5FtbTScen8',
    appId: '1:484992258162:android:8f68da6e394aec2eb2f2eb',
    messagingSenderId: '484992258162',
    projectId: 'notifi-536aa',
    storageBucket: 'notifi-536aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBqI1FbMH1ZHZE1RozYsq8Wo_XFsklyAE',
    appId: '1:484992258162:ios:edff0391ee41d1bfb2f2eb',
    messagingSenderId: '484992258162',
    projectId: 'notifi-536aa',
    storageBucket: 'notifi-536aa.firebasestorage.app',
    iosBundleId: 'com.example.caffeine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBqI1FbMH1ZHZE1RozYsq8Wo_XFsklyAE',
    appId: '1:484992258162:ios:edff0391ee41d1bfb2f2eb',
    messagingSenderId: '484992258162',
    projectId: 'notifi-536aa',
    storageBucket: 'notifi-536aa.firebasestorage.app',
    iosBundleId: 'com.example.caffeine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqBcJ-Ay6iAhhHmh5ma3BH9DJQXchOkE',
    appId: '1:484992258162:web:53f4a1461de192a6b2f2eb',
    messagingSenderId: '484992258162',
    projectId: 'notifi-536aa',
    authDomain: 'notifi-536aa.firebaseapp.com',
    storageBucket: 'notifi-536aa.firebasestorage.app',
    measurementId: 'G-83NV6FYQBY',
  );
}
