// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:caffeine/features/home/data/product_model.dart';
import 'package:caffeine/features/profile/data/user_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OfferModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(UserDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OfferModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(UserDataAdapter());
  }
}
